import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { mkdir, realpath } from 'node:fs/promises';
import { chromium, expect } from '@playwright/test';
import { createServer } from 'vite';

const desktop = fileURLToPath(new URL('..', import.meta.url));
const root = path.dirname(desktop.replace(/\/$/, ''));
const artifacts = path.join(root, 'artifacts/hac-165');
await mkdir(artifacts, { recursive: true });
const server = await createServer({ configFile: false, root: desktop, publicDir: path.join(root, 'public'), resolve: { dedupe: ['react', 'react-dom', '@radix-ui/react-select', '@phosphor-icons/react'], alias: { '@agentcloud-tokens': path.join(root, 'app/tokens.css') } }, server: { host: '127.0.0.1', port: 0, fs: { allow: [root, await realpath(path.join(root, 'node_modules'))] } }, esbuild: { jsx: 'automatic' } });
let browser;
try {
  await server.listen();
  const base = `http://127.0.0.1:${server.httpServer.address().port}`;
  browser = await chromium.launch({ headless: true, channel: process.env.PLAYWRIGHT_CHANNEL || 'chrome' });
  const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, permissions: ['clipboard-read', 'clipboard-write'] });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.addInitScript({ path: path.join(desktop, 'tests/chat-design.fixture.js') });
  await page.goto(base);
  async function selectEnvironment(name='cpu-workspace') {
    await page.getByRole('combobox', { name: 'Environment', exact: true }).first().click();
    await page.getByRole('option').filter({ hasText: name }).click();
  }
  await selectEnvironment();
  await expect(page.getByText("Replies come from this project's agent via alto.", { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Tasks', exact: true })).toHaveCount(0);
  await expect(page.getByText('What can I help with?', { exact: true })).toHaveCount(0);
  await expect(page.getByText('Local Codex box', { exact: true })).toHaveCount(0);
  const recovered = page.locator('details').filter({ hasText: 'Previous connection issues (2) · Resolved' });
  await expect(recovered).toBeVisible();
  await expect(recovered).not.toHaveAttribute('open');
  await expect(page.getByRole('alert')).toHaveCount(0);
  await recovered.locator('summary').click();
  await expect(recovered.locator('p')).toHaveCount(2);
  await expect(recovered.locator('p').first()).toBeVisible();
  await recovered.locator('summary').click();
  await page.evaluate(() => window.__test.events.s1.push({ id: 'current-connection-error', kind: 'error', text: 'Codex connection to the environment failed. Reconnect to continue.', updatedAt: new Date().toISOString() }, { id: 'execution-error', kind: 'error', text: 'Codex reported an execution error.', updatedAt: new Date().toISOString() }));
  await expect(page.getByRole('alert')).toHaveCount(2);
  await page.evaluate(() => window.__test.events.s1.splice(-2));
  await expect(page.getByRole('alert')).toHaveCount(0);
  async function layout(state) {
    for (const width of [375, 768, 1440]) {
      await page.setViewportSize({ width, height: 900 });
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
      expect(await page.locator('.conversation').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
      const composer = await page.locator('.composer-row').boundingBox();
      expect(composer.x + composer.width).toBeLessThanOrEqual(width);
      expect(composer.x).toBeGreaterThanOrEqual(0);
      const main = await page.locator('.project-chat-main').boundingBox();
      expect(Math.abs(composer.x + composer.width / 2 - main.x - main.width / 2)).toBeLessThan(1);
      const alignment = await page.locator('.conversation').evaluate(el => { const r = el.getBoundingClientRect(); const css = getComputedStyle(el); return { left: r.left + parseFloat(css.paddingLeft), right: r.right - parseFloat(css.paddingRight) }; });
      expect(Math.abs(composer.x - alignment.left)).toBeLessThan(1);
      expect(Math.abs(composer.x + composer.width - alignment.right)).toBeLessThan(1);
      expect(composer.y + composer.height).toBeLessThanOrEqual(900);
      await page.screenshot({ path: path.join(artifacts, `${state}-${width}.png`) });
    }
  }
  await layout('empty');
  const input = page.getByRole('textbox', { name: 'Message', exact: true });
  const notify = page.getByRole('button', { name: 'Notify agent', exact: true });
  await expect(notify).toBeDisabled();
  await input.fill('Coordinate the API integration.');
  await notify.click();
  await expect(page.getByText('Update queued for 1 other agent.', { exact: true })).toBeVisible();
  await expect(input).toHaveValue('');
  const broadcasts = await page.evaluate(() => window.__test.broadcasts);
  expect(broadcasts).toHaveLength(1);
  expect(broadcasts[0]).toMatchObject({ path: '/api/codex-sessions/s1/peer-messages', broadcast: true, text: 'Coordinate the API integration.' });
  expect(broadcasts[0].requestId).toMatch(/^[a-f0-9-]{36}$/);
  for (const width of [375, 768, 1440]) {
    await page.setViewportSize({ width, height: 900 });
    await expect(notify).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  }
  const longPrompt = 'For a local connection verification, inspect /home/node/workspace/agentcloud-connection-check.txt and report the exact contents without modifying files. '.repeat(3);
  await input.fill(longPrompt);
  await input.press('Shift+Enter');
  await input.pressSequentially('Keep the API stable.');
  await input.dispatchEvent('keydown', { key: 'Enter', code: 'Enter', isComposing: true });
  await expect(input).toHaveValue(`${longPrompt}\nKeep the API stable.`);
  await page.getByLabel('Choose text context files').setInputFiles({ name: 'notes.md', mimeType: 'text/markdown', buffer: Buffer.from('Use cursor pagination.') });
  await expect(page.getByRole('button', { name: 'Remove notes.md' })).toBeVisible();
  await page.getByRole('button', { name: 'Remove notes.md' }).click();
  await expect(page.getByRole('button', { name: 'Remove notes.md' })).toHaveCount(0);
  await page.getByLabel('Choose text context files').setInputFiles({ name: 'notes.md', mimeType: 'text/markdown', buffer: Buffer.from('Use cursor pagination.') });
  await page.getByRole('button', { name: 'Send message' }).click();
  await page.getByRole('button', { name: 'Copy code', exact: true }).waitFor();
  const originalText = await page.evaluate(() => window.__test.sends[0].text);
  expect(originalText).toContain('Attached context: notes.md\nUse cursor pagination.');
  await expect(page.locator('.hljs-keyword')).toHaveCount(1);
  await page.getByRole('button', { name: 'Copy code', exact: true }).click();
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe('// bounded results\nconst message = "ready";');
  await layout('active');
  await page.evaluate(()=>{window.__test.sessions.find(s=>s.id==='s1').status='stopped';});
  await page.setViewportSize({width:375,height:900});
  await page.getByRole('button',{name:'Reconnect',exact:true}).waitFor();
  for(const name of ['New project','Reconnect']) {
    const bounds=await page.getByRole('button',{name,exact:true}).boundingBox();
    expect(bounds.x).toBeGreaterThanOrEqual(0);
    expect(bounds.x+bounds.width).toBeLessThanOrEqual(375);
  }
  await page.evaluate(()=>{window.__test.sessions.find(s=>s.id==='s1').status='ready';});
  await expect(page.getByRole('button',{name:'Reconnect',exact:true})).toHaveCount(0);
  await page.setViewportSize({width:1440,height:900});
  // A lost Retry response must retain its idempotency key, and never consume an unrelated draft.
  await input.fill('Unrelated unsent draft');
  await page.evaluate(() => { window.__test.loseResponse = true; });
  await page.getByRole('button', { name: 'Retry', exact: true }).click();
  await expect(page.getByText('Test response lost', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Retry', exact: true }).click();
  await expect(page.locator('.message[data-role="user"]')).toHaveCount(2);
  const requests = await page.evaluate(() => window.__test.sends);
  expect(requests[1].requestId).toBe(requests[2].requestId);
  await expect(input).toHaveValue('Unrelated unsent draft');
  await page.evaluate(() => { window.__test.fail = true; });
  await page.getByRole('button', { name: 'Retry', exact: true }).last().click();
  await expect(page.getByRole('button', { name: 'Send as a new turn' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Send message' })).toBeDisabled();
  await page.evaluate(() => { window.__test.fail = false; });
  await page.getByRole('button', { name: 'Send as a new turn' }).click();
  await expect(page.getByRole('button', { name: 'Send as a new turn' })).toHaveCount(0);
  expect(await page.evaluate(() => window.__test.sends.at(-1).text)).toBe(originalText);
  await expect(input).toHaveValue('Unrelated unsent draft');
  // State alone never invents command results, a GPU, or an SSH connection.
  await page.evaluate(() => { window.__test.sessions.find(session => session.id === 's1').status = 'running'; window.__test.events.s1.push({ id: 'command', kind: 'command', text: 'Command running. Output is not saved.', updatedAt: new Date().toISOString() }); });
  await expect(page.getByText('Responding…', { exact: true })).toBeVisible();
  await expect(page.locator('.codex-streaming-cursor')).toHaveCount(1);
  await expect(input).toHaveValue('Unrelated unsent draft');
  await layout('streaming');
  await page.locator('.codex-command:not(.codex-connection-history) summary').click();
  await expect(page.locator('.codex-command:not(.codex-connection-history)')).toHaveAttribute('open', '');
  await page.getByRole('button', { name: 'Stop response' }).click();
  await expect(page.getByText('Turn interrupted', { exact: true })).toBeVisible();
  await expect(input).toHaveValue('Unrelated unsent draft');
  for (const width of [375, 768]) {
    await page.setViewportSize({ width, height: 900 });
    await page.keyboard.press('Meta+k');
    const search = page.getByRole('searchbox', { name: 'Search chats' });
    await expect(search).toBeFocused();
    await search.fill('no match');
    await expect(page.getByText('No chats match “no match”', { exact: true })).toBeVisible();
    await search.fill('');
    await page.getByRole('button', { name: 'Sign out' }).focus();
    await page.keyboard.press('Tab');
    await expect(page.locator('.shell-close')).toBeFocused();
    await page.keyboard.press('Escape');
    await expect(page.getByRole('button', { name: 'Open navigation' })).toBeFocused();
  }
  await expect(input).toHaveValue('Unrelated unsent draft');
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.getByLabel('Choose text context files').setInputFiles({ name: 'draft.md', mimeType: 'text/markdown', buffer: Buffer.from('Preserve this attachment.') });
  await page.getByRole('button', { name: 'review-agent', exact: false }).click();
  await expect(input).toHaveAttribute('placeholder', 'Ask review-agent to work on UI verification');
  await expect(input).toHaveValue('');
  await page.locator('.chat-history-item').filter({ hasText: 'For a local connection verification' }).click();
  await expect(input).toHaveValue('Unrelated unsent draft');
  await expect(page.getByRole('button', { name: 'Remove draft.md' })).toBeVisible();
  await page.evaluate(() => { window.__test.setupRequired = true; });
  await page.getByRole('button', { name: 'New chat', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Sign in with ChatGPT', exact: true })).toBeVisible();
  await page.evaluate(() => { window.__test.setupRequired = false; });
  await page.getByRole('button', { name: 'New chat', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Sign in with ChatGPT', exact: true })).toHaveCount(0);
  await expect(input).toHaveValue('');
  expect(await page.evaluate(() => window.__test.created.newChat)).toBe(true);
  expect(await page.evaluate(() => window.__test.created.runBoxId)).toBe('box-1');
  await input.fill('Independent chat history');
  await page.getByRole('button', { name: 'Send message' }).click();
  await expect(page.locator('.message[data-role="user"]')).toHaveCount(1);
  await selectEnvironment('second-workspace');
  await expect(page.locator('.chat-history-item')).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Sign in with ChatGPT', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'New chat', exact: true })).toBeDisabled();
  await selectEnvironment();
  await expect(page.locator('.chat-history-item').filter({ hasText: 'Independent chat history' })).toBeVisible();
  await page.reload();
  await selectEnvironment();
  await page.locator('.chat-history-item').filter({ hasText: 'Independent chat history' }).click();
  await expect(page.locator('.message[data-role="user"]')).toHaveCount(1);
  await expect(input).toHaveValue('');
  await page.evaluate(() => window.__test.deepLink({ ok: true, target: { projectId: 'p1', runBoxId: 'box-2' } }));
  await expect(page.getByRole('button', { name: 'Sign in with ChatGPT', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Environment terminal', exact: true })).toHaveCount(0);
  // Removed Tasks links route truthfully; never connect to an origin from a link.
  await page.evaluate(() => window.__test.deepLink({ ok: true, target: { projectId: 'p1', taskRunBoxId: 'box-1' } }));
  await expect(page.getByRole('heading', { name: 'Environment terminal', exact: true })).toBeVisible();
  await expect(page.getByText('Error · Test SSH unavailable', { exact: true })).toBeVisible();
  await page.evaluate(() => window.__test.deepLink({ ok: true, target: { projectId: 'p1', environmentId: 'legacy-catalog' } }));
  await expect(page.getByText('This legacy link names a catalog resource. Select its environment from the list below.', { exact: true })).toBeVisible();
  await page.evaluate(() => window.__test.deepLink({ ok: true, target: { projectId: 'p1', serverUrl: 'https://other.example.invalid' } }));
  await expect(page.getByText(/This link came from a different alto server/)).toBeVisible();
  await page.evaluate(()=>window.__test.deepLink({ok:true,target:{projectId:'missing-project'}}));
  await expect(page.getByRole('alert')).toContainText('linked project is not available');
  await page.goto(`${base}/?no-projects`);
  await expect(page.getByRole('heading', {name:'Create a project'})).toBeVisible();
  await expect(page.getByRole('link', {name:'Open website'})).toHaveCount(0);
  const create = page.getByRole('button', {name:'Create project',exact:true});
  await create.click();
  expect(await page.evaluate(()=>window.__test.projectRequests)).toBeUndefined();
  await page.getByLabel('Project name', {exact:true}).fill('Native project');
  await page.getByLabel('Git repository', {exact:true}).fill('http://github.com/example/repo');
  await create.click();
  expect(await page.evaluate(()=>window.__test.projectRequests)).toBeUndefined();
  await page.getByLabel('Git repository', {exact:true}).fill('https://github.com/example/repo');
  await page.getByRole('combobox',{name:'Template',exact:true}).click();
  await page.getByRole('option',{name:'Empty workspace',exact:true}).click();
  await page.getByRole('radio', {name:'SSH machine'}).check();
  await create.click();
  expect(await page.evaluate(()=>window.__test.projectRequests)).toBeUndefined();
  await page.getByLabel('SSH host', {exact:true}).fill('dev@example.com');
  for (const width of [375,768,1440]) {
    await page.setViewportSize({width,height:900});
    await create.scrollIntoViewIfNeeded();
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
    const bounds=await create.boundingBox();
    expect(bounds.y+bounds.height).toBeLessThanOrEqual(900);
    await create.focus();
    await expect(create).toBeFocused();
    await page.screenshot({path:path.join(artifacts,`create-project-${width}.png`)});
  }
  await page.evaluate(()=>{window.__test.projectFailure=true;});
  await create.click();
  await expect(page.getByRole('alert')).toContainText('Organization admin access required');
  await expect(page.getByLabel('Project name',{exact:true})).toHaveValue('Native project');
  await expect(page.getByLabel('SSH host',{exact:true})).toHaveValue('dev@example.com');
  await page.evaluate(()=>{window.__test.projectFailure=false;});
  await create.click();
  await expect(page.getByRole('combobox',{name:'Project',exact:true})).toHaveText('Native project');
  expect(await page.evaluate(()=>window.__test.projectRequests.at(-1))).toEqual({type:'createProject',name:'Native project',repo:'https://github.com/example/repo',template:'Empty workspace',compute:'SSH machine',host:'dev@example.com'});
  expect(await page.evaluate(()=>window.__test.created)).toBeUndefined();
  await page.getByRole('button',{name:'New project',exact:true}).click();
  await expect(page.getByRole('combobox',{name:'Existing project',exact:true})).toBeVisible();
  await page.getByRole('combobox',{name:'Existing project',exact:true}).click();
  await page.getByRole('option',{name:'Native project',exact:true}).click();
  await expect(page.getByRole('combobox',{name:'Project',exact:true})).toHaveText('Native project');
  await page.goto(`${base}/?no-projects`);
  await page.getByLabel('Project name',{exact:true}).fill('Hosted project');
  await page.getByLabel('Git repository',{exact:true}).fill('https://github.com/example/hosted');
  await create.click();
  await expect(page.getByRole('combobox',{name:'Project',exact:true})).toHaveText('Hosted project');
  expect(await page.evaluate(()=>window.__test.projectRequests.at(-1))).toEqual({type:'createProject',name:'Hosted project',repo:'https://github.com/example/hosted',template:'Next.js + Node API',compute:'Hosted Linux'});
  await page.goto(`${base}/?new-environment`);
  await expect(page.getByText('Choose an environment to access its chats.', { exact: true })).toBeVisible();
  await selectEnvironment();
  await expect(page.getByRole('button', { name: 'Sign in with ChatGPT', exact: true })).toBeVisible();
  for (const width of [375, 768, 1440]) {
    await page.setViewportSize({ width, height: 900 });
    const setup = page.getByRole('region', { name: 'Connect Codex' });
    await expect(setup).toBeVisible();
    const settings = setup.getByRole('link', { name: 'Project settings' });
    await expect(settings).toHaveAttribute('href', /projects\/p1\/settings#agent-setup$/);
    await settings.focus();
    await expect(settings).toBeFocused();
    expect(await settings.evaluate(el => getComputedStyle(el).textDecorationLine)).toBe('none');
    expect(await settings.evaluate(el => getComputedStyle(el).outlineStyle)).toBe('solid');
    const button = await setup.getByRole('button', { name: 'Sign in with ChatGPT' }).boundingBox();
    const card = await setup.boundingBox();
    expect(button.width).toBeLessThan(card.width);
    expect(button.x + button.width).toBeLessThanOrEqual(width);
    expect(await page.evaluate(() => getComputedStyle(document.documentElement).colorScheme)).toBe('light');
    await page.screenshot({ path: path.join(artifacts, `refined-setup-${width}.png`) });
  }
  expect(await page.evaluate(() => window.__test.created)).toBeUndefined();
  await page.getByRole('button', { name: 'Sign in with ChatGPT', exact: true }).click();
  await expect(page.getByText(/Finish signing in to ChatGPT/)).toBeVisible();
  expect(await page.evaluate(() => window.__test.created)).toEqual({ projectId: 'p1', runBoxId: 'box-1' });
  expect(await page.evaluate(() => window.__test.loginCalls.filter((call) => call !== 'tunnel:stop'))).toEqual(['browser', 'tunnel:start']);
  for (const width of [375, 768, 1440]) {
    await page.setViewportSize({ width, height: 900 });
    await expect(page.getByRole('button', { name: 'Cancel sign-in' })).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  }
  await page.getByRole('button', { name: 'Cancel sign-in' }).click();
  await expect(page.getByRole('heading', { name: 'Connect your ChatGPT account' })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Sign in with ChatGPT', exact: true })).toBeVisible();
  await page.evaluate(() => {
    window.__test.sessions.push({ id:'web-ready', projectId:'p1', agentId:'a1', status:'auth_required', error:null, title:'Web setup', isSetupSession:true, target:{kind:'runBox',runBoxId:'box-1',provider:'docker-local',profileId:'cpu-workspace',state:'ready'} });
    window.__test.events['web-ready']=[];
  });
  await expect(page.getByRole('button', { name: 'Send message' })).toBeDisabled();
  await expect(page.getByRole('button', { name: 'Sign in with ChatGPT', exact: true })).toBeVisible();
  await page.evaluate(() => { window.__test.sessions[0].status = 'ready'; });
  await expect(input).toBeEnabled();
  await expect(page.getByRole('link', { name: 'Add Codex in Settings' })).toHaveCount(0);
  await input.fill('Ready after web sign-in');
  await expect(page.getByRole('button', { name: 'Send message' })).toBeEnabled();
  await layout('setup-required');
  expect(errors).toEqual([]);
  console.log('PASS: responsive empty/active/streaming, safe context sending, Markdown copy, retry dedup/recovery, drafts, search/focus, session selection, legacy links and empty projects.');
} finally { await browser?.close(); await server.close(); }
