import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { mkdir, realpath } from 'node:fs/promises';
import { chromium, expect } from '@playwright/test';
import { createServer } from 'vite';

const desktop = fileURLToPath(new URL('..', import.meta.url));
const root = path.dirname(desktop.replace(/\/$/, ''));
const artifacts = path.join(root, 'artifacts/hac-165');
await mkdir(artifacts, { recursive: true });
const server = await createServer({ configFile: false, root: desktop, publicDir: path.join(root, 'public'), resolve: { dedupe: ['react', 'react-dom', '@radix-ui/react-select', '@phosphor-icons/react'], alias: { '@agentcloud-tokens': path.join(root, 'app/tokens.css') } }, server: { host: '127.0.0.1', port: 0, fs: { allow: [root, await realpath(path.join(root, 'node_modules')), await realpath(path.join(desktop, 'node_modules'))] } }, esbuild: { jsx: 'automatic' } });
let browser;
try {
  await server.listen();
  const base = `http://127.0.0.1:${server.httpServer.address().port}`;
  browser = await chromium.launch({ headless: true, channel: process.env.PLAYWRIGHT_CHANNEL || 'chrome' });
  const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, permissions: ['clipboard-read', 'clipboard-write'] });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.addInitScript({ path: path.join(desktop, 'tests/chat-design.fixture.js') });
  await page.goto(base);
  async function selectEnvironment(name='cpu-workspace') {
    await page.getByRole('combobox', { name: 'Environment', exact: true }).first().click();
    await page.getByRole('option').filter({ hasText: name }).click();
  }
  await selectEnvironment();
  const input=page.getByRole('textbox',{name:'Message',exact:true});
  const count=await page.locator('.chat-history-item').count();
  for(let n=0;n<3;n++)await page.getByRole('button',{name:'New chat',exact:true}).click();
  await page.waitForTimeout(1200);
  expect(await page.evaluate(()=>window.__test.created)).toBeUndefined();
  await expect(page.locator('.chat-history-item')).toHaveCount(count);
  await expect(input).toBeEnabled();
  await input.fill('First deliberate message');
  await page.getByRole('button',{name:'New chat',exact:true}).click();
  await expect(input).toHaveValue('First deliberate message');
  await page.getByRole('button',{name:'Send message',exact:true}).click();
  const first=page.locator('.chat-history-item').filter({hasText:'First deliberate message'});
  await expect(first).toBeVisible();
  await expect(page.locator('.chat-history-item')).toHaveCount(count+1);
  await expect(page.locator('.message[data-role="user"]')).toHaveCount(1);
  console.log('Explored lazy creation successfully');
  for(const width of [375,768,1440]) {
    await page.setViewportSize({width,height:900});
    if(width<=768)await page.getByRole('button',{name:'Open navigation',exact:true}).click();
    const trigger=page.getByRole('button',{name:/Chat actions for First deliberate message/});
    await trigger.click();
    await expect(page.getByRole('menuitem',{name:'Rename',exact:true})).toBeVisible();
    await page.keyboard.press('Escape');await expect(trigger).toBeFocused();
    await trigger.click();await page.getByRole('menuitem',{name:'Rename',exact:true}).click();
    await page.screenshot({path:path.join(artifacts,`chat-menu-${width}.png`)});
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
    await page.getByRole('button',{name:'Cancel',exact:true}).click();
    if(width<=768)await page.keyboard.press('Escape');
  }
  await page.getByRole('button',{name:/Chat actions for First deliberate message/}).click();
  await page.getByRole('menuitem',{name:'Rename',exact:true}).click();
  const nameInput=page.getByRole('textbox',{name:'Chat name',exact:true});
  await nameInput.fill('Renamed work');
  await page.evaluate(()=>window.__test.renameFailure=true);
  await page.getByRole('button',{name:'Save',exact:true}).click();
  await expect(page.getByText('Rename failed; try again').first()).toBeVisible();
  await expect(nameInput).toHaveValue('Renamed work');
  await page.evaluate(()=>window.__test.renameFailure=false);
  await page.getByRole('button',{name:'Save',exact:true}).click();
  await expect(page.locator('.chat-history-item').filter({hasText:'Renamed work'})).toBeVisible();
  await expect(page.getByRole('heading',{name:'Renamed work',exact:true})).toBeVisible();
  await input.fill('Another message');await page.getByRole('button',{name:'Send message',exact:true}).click();
  await expect(page.locator('.message[data-role="user"]')).toHaveCount(2);
  await expect(page.getByRole('heading',{name:'Renamed work',exact:true})).toBeVisible();
  await page.reload();await selectEnvironment();
  await page.locator('.chat-history-item').filter({hasText:'Renamed work'}).click();
  await expect(page.getByRole('heading',{name:'Renamed work',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Chat actions for Renamed work',exact:true}).click();
  await page.getByRole('menuitem',{name:'Delete',exact:true}).click();
  await page.getByRole('button',{name:'Cancel',exact:true}).click();
  await expect(page.locator('.chat-history-item').filter({hasText:'Renamed work'})).toBeVisible();
  await page.getByRole('button',{name:'Chat actions for Renamed work',exact:true}).click();
  await page.getByRole('menuitem',{name:'Delete',exact:true}).click();
  await page.evaluate(()=>window.__test.deleteFailure=true);
  await page.getByRole('button',{name:'Delete',exact:true}).click();
  await expect(page.getByText('Delete failed; try again').first()).toBeVisible();
  await expect(page.locator('.chat-history-item').filter({hasText:'Renamed work'})).toBeVisible();
  await page.evaluate(()=>window.__test.deleteFailure=false);
  await page.getByRole('button',{name:'Delete',exact:true}).click();
  await expect(page.locator('.chat-history-item')).toHaveCount(count);
  await expect(page.getByRole('textbox',{name:'Message',exact:true})).toHaveValue('');
  await page.reload();await selectEnvironment();
  await expect(page.locator('.chat-history-item').filter({hasText:'Renamed work'})).toHaveCount(0);
  // A lost first-send response retries the same chat and turn IDs.
  await page.getByRole('button',{name:'New chat',exact:true}).click();
  await input.fill('Retry first message');
  await page.evaluate(()=>window.__test.loseResponse=true);
  await page.getByRole('button',{name:'Send message',exact:true}).click();
  await expect(page.getByText('Test response lost',{exact:true})).toBeVisible();
  await expect(input).toHaveValue('Retry first message');
  await expect(page.locator('.chat-history-item')).toHaveCount(count);
  const before=await page.evaluate(()=>window.__test.sessions.length);
  await page.getByRole('button',{name:'Send message',exact:true}).click();
  await expect(page.locator('.message[data-role="user"]')).toHaveCount(1);
  expect(await page.evaluate(()=>window.__test.sessions.length)).toBe(before);
  const sends=await page.evaluate(()=>window.__test.sends.filter(x=>x.text==='Retry first message'));
  expect(sends[0].requestId).toBe(sends[1].requestId);
  await page.locator('.chat-history-item').filter({hasText:'review-agent'}).click();
  await page.getByRole('button',{name:'New chat',exact:true}).click();
  await input.fill('Recover an uncertain first send');
  await page.evaluate(()=>window.__test.fail=true);
  await page.getByRole('button',{name:'Send message',exact:true}).click();
  await expect(page.getByRole('button',{name:'Send as a new turn',exact:true})).toBeVisible();
  expect(await page.evaluate(()=>window.__test.created.agentId)).toBe('a2');
  await expect(input).toHaveValue('Recover an uncertain first send');
  await page.evaluate(()=>window.__test.fail=false);
  await page.getByRole('button',{name:'Send as a new turn',exact:true}).click();
  await expect(page.locator('.message[data-role="user"]')).toHaveCount(1);
  await expect(input).toHaveValue('');
  await page.getByRole('button',{name:/Chat actions for Recover an uncertain first send/}).click();
  await page.getByRole('menuitem',{name:'Rename',exact:true}).click();
  await page.getByRole('textbox',{name:'Chat name',exact:true}).fill('New chat');
  await page.getByRole('button',{name:'Save',exact:true}).click();
  await expect(page.getByRole('heading',{name:'New chat',exact:true})).toBeVisible();
  await page.waitForTimeout(1200);
  await expect(page.getByRole('heading',{name:'New chat',exact:true})).toBeVisible();
  console.log('PASS: lazy draft, one first-send chat, retry identity, rename/persistence, delete/cancel/failure/reload, keyboard and 375/768/1440 menus.');
  expect(errors).toEqual([]);
} finally {await browser?.close();await server.close();}
