import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { mkdir, realpath } from 'node:fs/promises';
import { chromium, expect } from '@playwright/test';
import { createServer } from 'vite';

const desktop = fileURLToPath(new URL('..', import.meta.url));
const root = path.dirname(desktop.replace(/\/$/, ''));
const artifacts = path.join(root, 'artifacts/hac-159');
await mkdir(artifacts, { recursive: true });
const server = await createServer({ configFile: false, root: desktop, publicDir: path.join(root, 'public'), resolve: { dedupe: ['react', 'react-dom', '@radix-ui/react-select', '@phosphor-icons/react'], alias: { '@agentcloud-tokens': path.join(root, 'app/tokens.css') } }, server: { host: '127.0.0.1', port: 0, fs: { allow: [root, await realpath(path.join(root, 'node_modules'))] } }, esbuild: { jsx: 'automatic' } });
let browser;
try {
  await server.listen();
  const base = `http://127.0.0.1:${server.httpServer.address().port}`;
  browser = await chromium.launch({ headless: true, channel: process.env.PLAYWRIGHT_CHANNEL || 'chrome' });
  const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, permissions: ['clipboard-read', 'clipboard-write'] });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.addInitScript({ path: path.join(desktop, 'tests/chat-design.fixture.js') });
  await page.goto(base);
  await expect(page.getByText('Choose a ready environment to chat with Codex.', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Tasks', exact: true })).toHaveCount(0);
  async function choose(name) {
    await page.getByRole('combobox', { name: 'Environment', exact: true }).click();
    await page.getByRole('option').filter({ hasText: name }).click();
  }
  await choose('cpu-workspace');
  const input = () => page.getByRole('textbox', { name: 'Message', exact: true });
  await input().fill('Inspect workspace');
  await page.getByLabel('Choose text context files').setInputFiles({ name: 'notes.md', mimeType: 'text/markdown', buffer: Buffer.from('Use cursor pagination.') });
  await page.getByRole('button', { name: 'Send message', exact: true }).click();
  await expect(page.getByText('Environment reply', { exact: true })).toBeVisible();
  expect(await page.evaluate(() => window.__test.sends[0].options.recordPrompt)).toContain('Attached context: notes.md');
  for (const width of [375, 768, 1440]) {
    await page.setViewportSize({ width, height: 900 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    const composer = await page.locator('.composer:visible').boundingBox();
    expect(composer.x).toBeGreaterThanOrEqual(0);
    expect(composer.x + composer.width).toBeLessThanOrEqual(width);
    expect(composer.y + composer.height).toBeLessThanOrEqual(900);
    await page.screenshot({ path: path.join(artifacts, `environment-chat-${width}.png`) });
  }
  await input().fill('Saved draft');
  await choose('box-2');
  await expect(input()).toHaveValue('');
  await choose('cpu-workspace');
  await expect(input()).toHaveValue('Saved draft');
  await page.evaluate(() => { window.__test.fail = true; });
  await page.getByRole('button', { name: 'Send message', exact: true }).click();
  await expect(page.getByText('Test SSH connection unavailable', { exact: true })).toBeVisible();
  await expect(input()).toHaveValue('Saved draft');
  await page.evaluate(() => { window.__test.fail = false; window.__test.hold = true; });
  await page.getByRole('button', { name: 'Send message', exact: true }).click();
  await expect(page.getByRole('combobox', { name: 'Environment', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Stop response', exact: true }).click();
  await expect(page.getByText('Stopped · remote process ended', { exact: true })).toBeVisible();
  await expect(page.getByRole('combobox', { name: 'Environment', exact: true })).toBeEnabled();
  await page.evaluate(() => window.__test.deepLink({ ok: true, target: { projectId: 'p1', codexSessionId: 'old-session' } }));
  await expect(page.getByText(/This legacy test-agent link is no longer used/)).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'Message', exact: true })).toHaveCount(0);
  await page.evaluate(() => window.__test.deepLink({ ok: true, target: { projectId: 'p1', runBoxId: 'box-1' } }));
  await expect(input()).toBeVisible();
  await page.evaluate(() => window.__test.deepLink({ ok: true, target: { projectId: 'p1', serverUrl: 'https://other.example.invalid' } }));
  await expect(page.getByText(/This link came from a different alto server/)).toBeVisible();
  await page.getByRole('button', { name: 'Environments', exact: true }).click();
  await page.getByRole('button', { name: 'Open chat', exact: true }).first().click();
  await expect(input()).toBeVisible();
  await page.evaluate(() => { window.__test.boxes[0].state = 'stopped'; window.__test.boxes[0].ssh = null; });
  await expect(page.getByText('This environment is not ready.', { exact: false })).toBeVisible({ timeout: 10000 });
  await input().fill('Must not run');
  await expect(page.getByRole('button', { name: 'Send message', exact: true })).toBeDisabled();
  await page.reload();
  await page.evaluate(() => { window.__test.signedIn = false; });
  await choose('cpu-workspace');
  await expect(page.getByRole('button', { name: 'Send message', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Sign in with ChatGPT', exact: true }).click();
  await expect(page.getByLabel('One-time code', { exact: true })).toHaveText('TEST-CODE');
  await expect(page.getByRole('combobox', { name: 'Environment', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Cancel sign-in', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Sign in with ChatGPT', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Sign in with ChatGPT', exact: true }).click();
  await page.evaluate(() => window.__test.emit({ type: 'signed-in', sessionId: 'login', runBoxId: 'box-1', detail: 'Signed in' }));
  await expect(page.getByRole('combobox', { name: 'Environment', exact: true })).toBeEnabled();
  await input().fill('Authenticated environment');
  await expect(page.getByRole('button', { name: 'Send message', exact: true })).toBeEnabled();
  expect(errors).toEqual([]);
  console.log('PASS: ready environment selection, early IPC events, remote replies, attachments, responsive layouts, preserved drafts, failed send, stop, legacy links, authenticated origin guard, environment navigation and stale readiness guard.');
} finally { await browser?.close(); await server.close(); }
